name: Dehumidifier control

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python control.py
        env:
          THINQ_PAT: ${{ secrets.THINQ_PAT }}
          THINQ_CLIENT_ID: ${{ secrets.THINQ_CLIENT_ID }}
          THINQ_DEVICE_ID: ${{ secrets.THINQ_DEVICE_ID }}
